# Análisis Exploratorio de Datos (EDA) – 20 Preguntas y Preguntas de Negocio

En este notebook se plantean 20 preguntas que combinan operaciones de filtrado y agrupación sobre el dataset de ventas de Adidas en EE.UU. Además, se incluyen preguntas de negocio para que los estudiantes deban abstraer y razonar sobre las implicaciones comerciales de los datos.

El ejercicio abarca:
- Análisis descriptivo básico (dimensiones, unidades de observación).
- Cálculo de totales, promedios y márgenes.
- Agrupaciones por Retailer, Estado, Producto y Método de Venta.
- Filtrados para extraer subconjuntos de datos.
- Preguntas de negocio para interpretar resultados y proponer soluciones basadas en la información.

¡Comienza resolviendo cada punto y analizando los resultados obtenidos!

In [1]:
!wget https://github.com/prayagpadwal/Adidas-Sales-Analysis/raw/main/Adidas%20US%20Sales%20Datasets.xlsx

--2025-03-06 20:25:34--  https://github.com/prayagpadwal/Adidas-Sales-Analysis/raw/main/Adidas%20US%20Sales%20Datasets.xlsx
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/prayagpadwal/Adidas-Sales-Analysis/main/Adidas%20US%20Sales%20Datasets.xlsx [following]
--2025-03-06 20:25:35--  https://raw.githubusercontent.com/prayagpadwal/Adidas-Sales-Analysis/main/Adidas%20US%20Sales%20Datasets.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 693038 (677K) [application/octet-stream]
Saving to: ‘Adidas US Sales Datasets.xlsx’

Adidas US Sales Dat 100%[===================>] 676.79K  3.54MB/s    in 0.2s

2025-03-06 20:25:36 (3.54 MB/s) - ‘Adidas US Sales Datasets.xlsx’ saved [693038/693038]

In [8]:
# Importar librerías necesarias
import pandas as pd
import numpy as np

# Leer el archivo Excel (asegúrate de haber subido 'Adidas US Sales Datasets.xlsx' a tu entorno de Colab)
data = pd.read_excel('Adidas US Sales Datasets.xlsx')

## Pregunta 1
**¿Cuántas filas y columnas tiene el dataset?**

_Muestra las dimensiones del DataFrame._

In [27]:
data

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.00,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.00,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.00,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.00,0.30,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Apparel,50.0,64,3200.0,896.00,0.28,Outlet
9644,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Women's Apparel,41.0,105,4305.0,1377.60,0.32,Outlet
9645,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184,7544.0,2791.28,0.37,Outlet
9646,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70,2940.0,1234.80,0.42,Outlet
9647,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Women's Street Footwear,29.0,83,2407.0,649.89,0.27,Outlet

In [12]:
data.shape

(9648, 13)

## Pregunta 2
**¿Cuál es la unidad de observación del dataset?**

_Describe qué representa cada fila (por ejemplo, una transacción o venta individual)._

Ventas de articulos de ropa y zapatos de la marca Adidas en Estados Unidos a comerciantes grandes.

In [88]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9648 non-null   object
 1   Retailer ID       9648 non-null   int64
 2   Invoice Date      9648 non-null   datetime64[ns]
 3   Region            9648 non-null   object
 4   State             9648 non-null   object
 5   City              9648 non-null   object
 6   Product           9648 non-null   object
 7   Price per Unit    9648 non-null   float64
 8   Units Sold        9648 non-null   int64
 9   Total Sales       9648 non-null   float64
 10  Operating Profit  9648 non-null   float64
 11  Operating Margin  9648 non-null   float64
 12  Sales Method      9648 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(6)
memory usage: 980.0+ KB

## Pregunta 3
**¿Cuáles fueron las ventas totales?**

_Suma de la columna 'Total Sales'._

In [24]:
data["Total Sales"].sum()

899902125.0

## Pregunta 4
**¿Cuál fue la ganancia operativa total?**

_Suma de la columna 'Operating Profit'._

In [25]:
data["Operating Profit"].sum()

332134761.45000005

## Pregunta 5
**¿Cuál es el margen operativo promedio?**

_Calcula la media de la columna 'Operating Margin' y explica por qué se utiliza el promedio en lugar de una suma._

In [55]:
data["Operating Margin"].mean()

0.42299129353233833

Porque el promedio se utiliza para obtener una mejor representación del margen operativo en un periodo especificp o entre diferentes comerciantes

## Pregunta 6
**Agrupar por Retailer y calcular:**
- La suma de 'Total Sales'
- La suma de 'Operating Profit'
- La suma de 'Units Sold'

_Utiliza `groupby` para obtener estos totales por cada Retailer._

In [31]:
data.groupby(["Retailer"])[["Total Sales","Operating Profit","Units Sold"]].sum()

               Total Sales  Operating Profit  Units Sold
Retailer
Amazon          77698912.0       28818503.31      197990
Foot Locker    220094720.0       80722124.81      604369
Kohl's         102114753.0       36811252.58      287375
Sports Direct  182470997.0       74332954.96      557640
Walmart         74558410.0       25782052.61      206225
West Gear      242964333.0       85667873.18      625262

## Pregunta 7
**Calcular el margen total por Retailer y el margen operativo promedio por Retailer.**

- Margen total: (Suma de 'Operating Profit' / Suma de 'Total Sales') por Retailer.
- Margen promedio: Promedio de la columna 'Operating Margin' para cada Retailer.

_Compara ambos resultados y comenta la diferencia, reflexionando sobre el significado en términos de negocio._

In [59]:
df=data.groupby(["Retailer"])[["Operating Profit","Total Sales"]].sum()

In [60]:
df.reset_index()

        Retailer  Operating Profit  Total Sales
0         Amazon       28818503.31   77698912.0
1    Foot Locker       80722124.81  220094720.0
2         Kohl's       36811252.58  102114753.0
3  Sports Direct       74332954.96  182470997.0
4        Walmart       25782052.61   74558410.0
5      West Gear       85667873.18  242964333.0

In [61]:
df["Margen Total"]=df["Operating Profit"]/df["Total Sales"]
df

               Operating Profit  Total Sales  Margen Total
Retailer
Amazon              28818503.31   77698912.0      0.370900
Foot Locker         80722124.81  220094720.0      0.366761
Kohl's              36811252.58  102114753.0      0.360489
Sports Direct       74332954.96  182470997.0      0.407369
Walmart             25782052.61   74558410.0      0.345797
West Gear           85667873.18  242964333.0      0.352594

In [63]:
data.groupby(["Retailer"])[["Operating Margin"]].mean()

               Operating Margin
Retailer
Amazon                 0.417871
Foot Locker            0.417933
Kohl's                 0.419291
Sports Direct          0.444892
Walmart                0.406534
West Gear              0.417856

El margen total sirve para dar una visión general de la rentabilidad total generada por cada comerciante, mientras que el margen promedio asigna la misma ponderación a cada transacción, independientemente del volumen de ventas. Ambas metricas son utiles en un negocio independientemente de lo que se quiera analizar y hallar, si se quiere saber el margen basado en ventas seria mas acertado usar el margen total pero si se quiere saber y comparar los margenes operativos en promedio por comerciante seria mejor usar el margen promedio.

## Pregunta 8
**¿Qué Retailer vendió la mayor cantidad de unidades totales?**

_Agrupa por Retailer, suma 'Units Sold' y ordena de forma descendente._

In [65]:
data.groupby("Retailer")["Units Sold"].sum().sort_values(ascending=False)

Retailer
West Gear        625262
Foot Locker      604369
Sports Direct    557640
Kohl's           287375
Walmart          206225
Amazon           197990
Name: Units Sold, dtype: int64

## Pregunta 9
**¿Qué producto vendió la mayor cantidad de unidades?**

_Agrupa por 'Product' y suma 'Units Sold' para identificar el producto líder._

In [66]:
data.groupby("Product")["Units Sold"].sum().sort_values(ascending=False)

Product
Men's Street Footwear        593320
Men's Athletic Footwear      435526
Women's Apparel              433827
Women's Street Footwear      392269
Women's Athletic Footwear    317236
Men's Apparel                306683
Name: Units Sold, dtype: int64

## Pregunta 10
**Agrupar por el método de venta ('Sales Method') y calcular:**
- La suma de 'Total Sales'
- El promedio de 'Total Sales'

_Esta agrupación ayudará a identificar cuál método tiene mejores resultados en términos de volumen y eficiencia._

In [73]:
data.groupby("Sales Method").agg({"Total Sales":["sum", "mean"]})

              Total Sales
                      sum           mean
Sales Method
In-store      356643750.0  204967.672414
Online        247672882.0   50659.210882
Outlet        295585493.0   97908.411063

## Pregunta 11
**¿Qué método de venta tiene mayores ventas totales y mayores ventas promedio?**

_Analiza los resultados obtenidos en la Pregunta 10 y comenta posibles razones de negocio detrás de estos resultados._

El metodo de venta con mayores ventas totales es In-Store
y el metodo de venta con mayores venta promedio es In-Store. Esto puede darse debido a que a la tienda fisica llega un mayor trafico de clientes, a que manejan precios mas altos a comparacion de los otros metodos de venta, a que los clientes tienen preferencia de este lugar por su comodidad y experiencia personalizada y/o facil o porque la tienda fisica tiene mejores estrategias de venta que los clientes prefieren

## Pregunta 12
**Agrupar por State y calcular la suma de 'Total Sales'.**

_Determina cuál es el estado con mayores ventas totales._

In [75]:
data.groupby("State")["Total Sales"].sum().sort_values(ascending=False)

State
New York          64229039.0
California        60174133.0
Florida           59283714.0
Texas             46359746.0
South Carolina    29285637.0
Washington        26330718.0
North Carolina    23956531.0
Louisiana         23750781.0
Hawaii            22282457.0
Virginia          21575040.0
Oregon            21349674.0
Colorado          20996536.0
Nevada            20858509.0
New Mexico        19865016.0
Idaho             19276878.0
Georgia           18997466.0
Michigan          18625433.0
Wyoming           18577517.0
Ohio              18484583.0
Tennessee         18067440.0
Alabama           17633424.0
New Hampshire     16411667.0
Arizona           15782221.0
Montana           15710886.0
Mississippi       15591709.0
Alaska            14753103.0
Vermont           14352923.0
Arkansas          12639347.0
Delaware          12298412.0
Connecticut       11573448.0
Massachusetts     11076810.0
West Virginia     10689160.0
Oklahoma          10620734.0
Pennsylvania      10357519.0
Kentucky          10072848.0
Kansas             9972864.0
New Jersey         9934246.0
Illinois           9797488.0
Utah               9696420.0
Missouri           9683265.0
Maine              9195978.0
Indiana            8836198.0
South Dakota       8495576.0
Rhode Island       8446806.0
Maryland           7758059.0
North Dakota       7735580.0
Wisconsin          7727469.0
Iowa               7424011.0
Minnesota          7378068.0
Nebraska           5929038.0
Name: Total Sales, dtype: float64

## Pregunta 13 (Negocio)
**¿Qué estado muestra un mejor desempeño operativo?**

_Agrupa por State y calcula el promedio de 'Operating Margin' para evaluar cuál estado opera de manera más eficiente. Comenta posibles implicaciones de negocio._

In [76]:
data.groupby("State")["Operating Margin"].mean().sort_values(ascending=False)

State
Alabama           0.553565
Tennessee         0.506574
Michigan          0.475764
Montana           0.471042
North Carolina    0.463542
Ohio              0.459028
Idaho             0.458935
Nebraska          0.457917
West Virginia     0.456806
Mississippi       0.454306
Missouri          0.453194
Illinois          0.449514
Texas             0.449144
Kentucky          0.448611
Louisiana         0.446852
Utah              0.444676
Vermont           0.444259
Arkansas          0.440509
Oklahoma          0.435093
Indiana           0.433889
South Carolina    0.433056
Delaware          0.427986
Colorado          0.427083
New Jersey        0.427083
Pennsylvania      0.425880
Wisconsin         0.424236
Iowa              0.420903
Virginia          0.414398
Georgia           0.413704
Oregon            0.413611
Rhode Island      0.412361
Kansas            0.411667
New York          0.408333
Minnesota         0.408125
Maryland          0.407431
Nevada            0.405926
Wyoming           0.402778
Connecticut       0.401620
Maine             0.398889
North Dakota      0.398611
South Dakota      0.394653
New Mexico        0.392917
New Hampshire     0.391019
Florida           0.390222
Arizona           0.389815
California        0.386852
Alaska            0.349861
Massachusetts     0.347130
Washington        0.325069
Hawaii            0.319583
Name: Operating Margin, dtype: float64

Teniendo en cuenta que el estado que opera de manera mas eficiente es Alabama, esto se puede deber a que son mejores en su manejo de logistica, mas acertados en los precios que ofrecen y debido a su variedad de productos que venden, lo que hace que el cliente demande y prefiera sus productos

## Pregunta 14
**Filtro 1: Crea un DataFrame filtrado para el Retailer con mayores ventas totales.**

_Utiliza la agrupación previa para identificar dicho Retailer y filtra el dataset original._

In [77]:
data.groupby("Retailer")["Total Sales"].sum().sort_values(ascending=False)

Retailer
West Gear        242964333.0
Foot Locker      220094720.0
Sports Direct    182470997.0
Kohl's           102114753.0
Amazon            77698912.0
Walmart           74558410.0
Name: Total Sales, dtype: float64

In [82]:
mejor=data[data["Retailer"]=="West Gear"]
mejor

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
140,West Gear,1128299,2020-11-01,South,Texas,Houston,Men's Street Footwear,40.0,775,310000.0,108500.00,0.35,Outlet
141,West Gear,1128299,2020-11-02,South,Texas,Houston,Men's Athletic Footwear,50.0,775,387500.0,77500.00,0.20,Outlet
142,West Gear,1128299,2020-11-03,South,Texas,Houston,Women's Street Footwear,50.0,775,387500.0,135625.00,0.35,Outlet
143,West Gear,1128299,2020-11-04,South,Texas,Houston,Women's Athletic Footwear,50.0,625,312500.0,93750.00,0.30,Outlet
144,West Gear,1128299,2020-11-05,West,California,San Francisco,Men's Apparel,55.0,575,316250.0,158125.00,0.50,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9265,West Gear,1197831,2021-10-21,South,Oklahoma,Oklahoma City,Men's Apparel,22.0,68,1496.0,568.48,0.38,Outlet
9554,West Gear,1185732,2021-10-12,Northeast,Vermont,Burlington,Women's Apparel,54.0,90,4860.0,2235.60,0.46,Outlet
9555,West Gear,1185732,2021-11-11,Northeast,Vermont,Burlington,Men's Street Footwear,54.0,140,7560.0,3780.00,0.50,Outlet
9556,West Gear,1185732,2021-11-11,Northeast,Vermont,Burlington,Men's Athletic Footwear,47.0,98,4606.0,2256.94,0.49,Outlet
9557,West Gear,1185732,2021-11-11,Northeast,Vermont,Burlington,Women's Street Footwear,46.0,102,4692.0,1736.04,0.37,Outlet

## Pregunta 15
**Filtro 2: Crea un DataFrame filtrado para el estado con mayores ventas totales.**

_Utiliza la agrupación por State para identificar dicho estado y filtra el dataset original._

In [83]:
data.groupby("State")["Total Sales"].sum().sort_values(ascending=False)

State
New York          64229039.0
California        60174133.0
Florida           59283714.0
Texas             46359746.0
South Carolina    29285637.0
Washington        26330718.0
North Carolina    23956531.0
Louisiana         23750781.0
Hawaii            22282457.0
Virginia          21575040.0
Oregon            21349674.0
Colorado          20996536.0
Nevada            20858509.0
New Mexico        19865016.0
Idaho             19276878.0
Georgia           18997466.0
Michigan          18625433.0
Wyoming           18577517.0
Ohio              18484583.0
Tennessee         18067440.0
Alabama           17633424.0
New Hampshire     16411667.0
Arizona           15782221.0
Montana           15710886.0
Mississippi       15591709.0
Alaska            14753103.0
Vermont           14352923.0
Arkansas          12639347.0
Delaware          12298412.0
Connecticut       11573448.0
Massachusetts     11076810.0
West Virginia     10689160.0
Oklahoma          10620734.0
Pennsylvania      10357519.0
Kentucky          10072848.0
Kansas             9972864.0
New Jersey         9934246.0
Illinois           9797488.0
Utah               9696420.0
Missouri           9683265.0
Maine              9195978.0
Indiana            8836198.0
South Dakota       8495576.0
Rhode Island       8446806.0
Maryland           7758059.0
North Dakota       7735580.0
Wisconsin          7727469.0
Iowa               7424011.0
Minnesota          7378068.0
Nebraska           5929038.0
Name: Total Sales, dtype: float64

In [84]:
mejorestado=data[data["State"]=="New York"]
mejorestado

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.00,0.30,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.00,0.35,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.00,0.35,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.00,0.30,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7843,Walmart,1185732,2020-07-18,Northeast,New York,New York,Women's Apparel,48.0,340,16320.0,4896.00,0.30,Outlet
7844,Sports Direct,1197831,2020-07-19,Northeast,New York,New York,Men's Street Footwear,20.0,270,5400.0,2106.00,0.39,Outlet
7845,Sports Direct,1197831,2020-07-20,Northeast,New York,New York,Men's Athletic Footwear,26.0,270,7020.0,2597.40,0.37,Outlet
7846,Sports Direct,1197831,2020-07-21,Northeast,New York,New York,Women's Street Footwear,27.0,238,6426.0,2506.14,0.39,Outlet
7847,Sports Direct,1197831,2020-07-22,Northeast,New York,New York,Women's Athletic Footwear,27.0,210,5670.0,2948.40,0.52,Outlet

## Pregunta 16
**Filtro 3: Crea un DataFrame filtrado para el producto con mayor cantidad de unidades vendidas.**

_Identifica el producto líder y extrae las transacciones relacionadas._

In [89]:
data.groupby("Product")["Units Sold"].sum().sort_values(ascending=False)

Product
Men's Street Footwear        593320
Men's Athletic Footwear      435526
Women's Apparel              433827
Women's Street Footwear      392269
Women's Athletic Footwear    317236
Men's Apparel                306683
Name: Units Sold, dtype: int64

In [90]:
mejorproducto=data[data["Product"]=="Men's Street Footwear"]
mejorproducto

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,In-store
6,Foot Locker,1185732,2020-01-07,Northeast,New York,New York,Men's Street Footwear,50.0,1250,625000.0,312500.00,0.50,In-store
12,Foot Locker,1185732,2020-01-25,Northeast,New York,New York,Men's Street Footwear,50.0,1220,610000.0,305000.00,0.50,Outlet
18,Foot Locker,1185732,2020-01-31,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.00,0.50,Outlet
24,Foot Locker,1185732,2020-02-06,Northeast,New York,New York,Men's Street Footwear,60.0,1220,732000.0,366000.00,0.50,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9621,Foot Locker,1185732,2021-10-19,Northeast,New Hampshire,Manchester,Men's Street Footwear,52.0,162,8424.0,3538.08,0.42,Outlet
9627,Foot Locker,1185732,2021-11-18,Northeast,New Hampshire,Manchester,Men's Street Footwear,59.0,149,8791.0,3780.13,0.43,Outlet
9633,Foot Locker,1185732,2021-12-17,Northeast,New Hampshire,Manchester,Men's Street Footwear,49.0,200,9800.0,4606.00,0.47,Outlet
9639,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Street Footwear,36.0,165,5940.0,2197.80,0.37,Outlet
9645,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184,7544.0,2791.28,0.37,Outlet

## Pregunta 17 (Negocio)
**¿Qué Retailer presenta el mayor margen operativo y por qué podría ser significativo desde el punto de vista del negocio?**

_Analiza el resumen por Retailer y discute las posibles implicaciones (por ejemplo, eficiencia operativa, estrategia de precios, etc.)._

In [112]:
df

               Operating Profit  Total Sales  Margen Total
Retailer
Amazon              28818503.31   77698912.0      0.370900
Foot Locker         80722124.81  220094720.0      0.366761
Kohl's              36811252.58  102114753.0      0.360489
Sports Direct       74332954.96  182470997.0      0.407369
Walmart             25782052.61   74558410.0      0.345797
West Gear           85667873.18  242964333.0      0.352594

El retailer con mayor margen operativo es Sports Direct, lo cual podemos comparar con el retailer que mas ventas totales tiene que es West Gear. Esto nos demuestra que aunque Sports Direct tenga mejor margen operativo, no son los mejores en generar ingresos o ganancias tal vez por sus costos de produccion o sus inversiones en otras instancias que les quitan ganancias.

## Pregunta 18 (Negocio)
**Analiza el desempeño entre métodos de venta (por ejemplo, In-store vs. Online si aplica).**

_Si el dataset incluye ambos métodos, comenta sobre las posibles diferencias en ventas totales y promedios y qué implicaciones podrían tener en la estrategia comercial._

In [113]:
data.groupby("Sales Method").agg({"Total Sales":["sum", "mean"]})

              Total Sales
                      sum           mean
Sales Method
In-store      356643750.0  204967.672414
Online        247672882.0   50659.210882
Outlet        295585493.0   97908.411063

Las ventas "In-store" dominan claramente, representando la mayor parte de las ventas totales.
Las ventas "Online" le siguen, con una cantidad significativa, pero menor.
Las ventas en outlets "Outlet" son las más bajas.
Esto puede ser porque en los outlets no hay atencion personalizada ni mucha variedad de productos, para la tienda online como se encuentra en segundo lugar puede ser porque manejan precios mas bajos por promociones o la facilidad de encontrar un articulo de manera rapida, y en la tienda fisica los clientes tienen preferencia de este lugar por su comodidad y experiencia personalizada

## Pregunta 19
**Filtro Combinado: Crea un DataFrame filtrado que cumpla con los siguientes criterios:**
- Retailer con mayores ventas totales
- Estado con mayores ventas totales
- Producto con mayor cantidad de unidades vendidas
- Método de venta con mayores ventas totales

_Muestra las primeras filas del DataFrame resultante._

In [107]:
combi=data[(data["Retailer"]=="West Gear") & (data["State"]=="New York") & (data["Product"]=="Men's Street Footwear") & (data["Sales Method"]=="In-store")].reset_index(drop=True)
combi.head(5)

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,West Gear,1185732,2021-03-08,Northeast,New York,Albany,Men's Street Footwear,45.0,870,391500.0,176175.0,0.45,In-store
1,West Gear,1185732,2021-04-09,Northeast,New York,Albany,Men's Street Footwear,45.0,825,371250.0,167062.5,0.45,In-store
2,West Gear,1185732,2021-05-08,Northeast,New York,Albany,Men's Street Footwear,55.0,870,478500.0,215325.0,0.45,In-store
3,West Gear,1185732,2021-06-10,Northeast,New York,Albany,Men's Street Footwear,60.0,875,525000.0,236250.0,0.45,In-store
4,West Gear,1185732,2021-07-08,Northeast,New York,Albany,Men's Street Footwear,65.0,950,617500.0,277875.0,0.45,In-store

## Pregunta 20 (Negocio)
**Basado en el análisis de las variables (ventas, margen, unidades vendidas) y la matriz de correlación (si se llegase a calcular en un análisis posterior), ¿cuáles crees que son los principales factores que contribuyen a la ganancia operativa?**

_Esta pregunta es abierta: reflexiona sobre la relación entre precio por unidad, unidades vendidas, ventas totales y margen operativo, y plantea posibles estrategias de negocio basadas en estos insights._

La relación entre el precio por unidad, las unidades vendidas, las ventas totales y el margen de beneficio son esenciales para la estrategia empresarial.  Debido a que un precio elevado puede incrementar la rentabilidad, pero disminuir las ventas, un precio muy bajo puede aumentar las ventas, pero disminuir la rentabilidad.  Las ventas totales son la relacion entre el precio y las unidades que se venden, mientras que el margen operativo muestra la rentabilidad real despues de restarle los costos.  Las mejores estrategias buscan enfocarse en productos de alta calidad con alto margen y bajo volumen, hasta productos de bajo margen y alto volumen, optimizar costos, precios dinámicos y diversificación de catalogo.

## Conclusión

En este notebook se han planteado 20 preguntas que combinan análisis técnico y reflexiones de negocio. Se ha trabajado con filtrados y agrupaciones para extraer insights clave del dataset de ventas, lo que permite a los estudiantes practicar y comprender cómo los datos pueden informar decisiones estratégicas en un entorno comercial.